spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flipcartdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: flipcartdb
      username: root
      password: root

server:
  port: 7200
